pub mod bluetooth;
pub mod capslock;
pub mod hotkey;
pub mod hyprland;
pub mod notifications;
pub mod numlock;
pub mod osd_events;
pub mod pipewire;
pub mod pomodoro;
pub mod speech;
pub mod systray;

pub use bluetooth::{BluetoothService, BluetoothState};
pub use capslock::CapsLockService;
pub use hotkey::ToggleDictation;
pub use hyprland::HyprlandService;
pub use notifications::{Notification, NotificationService, NotificationManager};
pub use numlock::NumLockService;
pub use osd_events::{OsdEvent, OsdEventService, receive_osd_events};
pub use pipewire::PipeWireService;
pub use pomodoro::{PomodoroService, PomodoroState};
pub use speech::SpeechRecognitionService;
pub use systray::{SystemTrayService, TrayItem};
